# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "mexBuildWithActions" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mexBuild:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        MATLABVersion: [R2024b]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.MATLABVersion }}
      - name: Run script
        uses: matlab-actions/run-command@v2
        with:
          command: buildtool mex
      - name: Upload MEX
        uses: actions/upload-artifact@v4
        with:
          name: MEX_${{ matrix.os }}
          path: toolbox/private
    
  package:
    needs: mexBuild
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: MEX_ubuntu-latest
          path: toolbox/private
      - uses: actions/download-artifact@v4
        with:
          name: MEX_windows-latest
          path: toolbox/private
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024b
      - name: Run script
        uses: matlab-actions/run-command@v2
        with:
          command: buildtool release
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          draft: true        
          artifacts: "release/Arithmetic_Toolbox.mltbx"
          generateReleaseNotes: true